
--1.What is the total revenue generated by male vs. female customers?
   
   select * from dbo.[clean_customer_shopping_behavior.csv]

   select gender,sum(purchase_amount) as Revenue from dbo.[clean_customer_shopping_behavior.csv]
   group by gender

--2.Which customers used a discount but still spent more than the average purchase amount?

   select customer_id,purchase_amount from dbo.[clean_customer_shopping_behavior.csv]
   where discount_applied='Yes' and
   purchase_amount>(select avg(purchase_amount) from dbo.[clean_customer_shopping_behavior.csv])
   
--3.Which are the top 5 products with the highest average review rating?

   select Top 5 item_purchased ,avg(review_rating) average_rating from dbo.[clean_customer_shopping_behavior.csv]
   group by item_purchased 
   order by avg(review_rating) desc

--4.Compare the average purchase amounts between Standard and Express shipping.

   select shipping_type,Round(avg(purchase_amount),2) from dbo.[clean_customer_shopping_behavior.csv]
   where shipping_type in ('Standard','Express')
   group by shipping_type

--5.Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
  
   select subscription_status,count(customer_id) as total_customer,
   avg(purchase_amount) as average_spend,sum(purchase_amount) as total_revenue 
   from dbo.[clean_customer_shopping_behavior.csv]
   group by subscription_status

--6.Which 5 products have the highest percentage of purchases with discounts applied?
   
   select top 5 item_purchased,
             (count(case when discount_applied='Yes' Then 1 End)*100/count(1)) as purchase_percent 
   from dbo.[clean_customer_shopping_behavior.csv]
   group by item_purchased
   order by purchase_percent desc

--7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
--and show the count of each segment.
  
  select case when previous_purchases=1 then 'Low'
              when previous_purchases between 2 and 10 then 'Returning'
              else 'Royal'
              end as customer_segment,
         count(1) as customer_count
 from dbo.[clean_customer_shopping_behavior.csv]
 group by 
         case when previous_purchases=1 then 'Low'
              when previous_purchases between 2 and 10 then 'Returning'
              else 'Royal'
              end
order by customer_count desc



--8.What are the top 3 most purchased products within each category?
  
  select *
   from (select Row_number() over (partition by category order by count(1) desc) as rnk,
         category,item_purchased,
         count(1) as total_orders
  from dbo.[clean_customer_shopping_behavior.csv]
  group by category,item_purchased) as t
  where rnk<=3

--9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

  select subscription_status,
         count(customer_id) repeat_buyers
  from dbo.[clean_customer_shopping_behavior.csv]
  where previous_purchases>5
  group by subscription_status

--10.What is the revenue contribution of each age group?
 
  Update dbo.[clean_customer_shopping_behavior.csv]
  set age_group='Young Adult'
  where age=18    /*I identified null values in the age_group column and filled them by creating 
                      age-based segments using SQL, ensuring no missing data before performing analysis.*/

  select age_group,sum(purchase_amount) from dbo.[clean_customer_shopping_behavior.csv]
  group by age_group


 
